name: Build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  hello:
    name: Hello
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: echo
        run: echo hello
