name: Build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  hello:
    name: Hello
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - name: Prepare
        run: mv bot-config.json.example bot-config.json

      - name: Tag
        uses: olegtarasov/get-tag@v2
      - name: Sha
        uses: benjlevesque/short-sha@v3.0

      - name: Publish docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}:sha-${{ env.SHA }}

      - name: Publish docker image with tag
        uses: docker/build-push-action@v6
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          push: true
          context: .
          tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}:${{ env.GIT_TAG_NAME }}
