---
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
# yamllint disable-line rule:truthy
on: [push]

jobs:
  npm-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    timeout-minutes: 5
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install Packages
        run: npm install
      - name: Create Bot Config
        run: cp bot-config.json.example bot-config.json
      - name: Standard Tests
        run: npm test
